// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.10.211
// </auto-generated>
// ------------------------------------------------------------------------------
namespace SurroundSelection
{
    static class Vsix
    {
        public const string Id = "4c807d55-9263-4ce0-9c1a-bfef58e96b02";
        public const string Name = "Surround Selection";
        public const string Description = @"The quickest way to wrap some selected text with various delimiters like double quotes, single quotes, braces etc.";
        public const string Language = "en-US";
        public const string Version = "2.0";
        public const string Author = "Priyanshu Agrawal";
        public const string Tags = "surround, wrap, quotes, delimiters";
    }
}
