// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.10.188
// </auto-generated>
// ------------------------------------------------------------------------------
namespace SurroundSelection
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidDoubleQuotesCommandPackageString = "cd3130df-8656-4af0-a2d4-d8f36a0eb7d0";
        public const string guidDoubleQuotesCommandPackageCmdSetString = "47bb1886-9d77-482b-9d50-1c10507119ee";
        public const string guidImagesString = "8ad9d13c-0ef8-4a2d-829e-0f48ed5ef4b0";
        public const string guidDoubleQuotesCommandPackageCmdSet1String = "1779ad3b-0e47-4e85-8c91-2bd2a0d824df";
        public const string guidDoubleQuotesCommandPackageCmdSet2String = "e0890da8-38a4-4db1-bbaa-93ba450cf9a9";
        public const string guidImages3String = "53ffedf0-7706-4d32-9774-cce7be32f013";
        public static Guid guidDoubleQuotesCommandPackage = new Guid(guidDoubleQuotesCommandPackageString);
        public static Guid guidDoubleQuotesCommandPackageCmdSet = new Guid(guidDoubleQuotesCommandPackageCmdSetString);
        public static Guid guidImages = new Guid(guidImagesString);
        public static Guid guidDoubleQuotesCommandPackageCmdSet1 = new Guid(guidDoubleQuotesCommandPackageCmdSet1String);
        public static Guid guidDoubleQuotesCommandPackageCmdSet2 = new Guid(guidDoubleQuotesCommandPackageCmdSet2String);
        public static Guid guidImages3 = new Guid(guidImages3String);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int MyMenuGroup = 0x1020;
        public const int DoubleQuotesCommandId = 0x0100;
        public const int SubMenuId = 0x0100;
        public const int SubMenu = 0x1100;
        public const int SubMenuGroup = 0x1150;
        public const int QuotesGroup = 0x1250;
        public const int BracketsGroup = 0x1350;
        public const int bmpPic1 = 0x0001;
        public const int MyMenuGroup2 = 0x1020;
        public const int cmdidSingleQuotesCommand = 0x0100;
        public const int MyMenuGroup3 = 0x1020;
        public const int cmdidBracesCommand = 0x0100;
        public const int cmdidParenthesis = 0x1021;
        public const int cmdidSquareBracketsCommand = 0x1022;
        public const int cmdidAngularBrackets = 0x1023;
        public const int cmdidAsteriskCommand = 0x1024;
        public const int bmpPic2 = 0x0001;
    }
}
